---

services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - laravel
    depends_on:
      - mysql
      - init
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_START_WITH_REQUEST=yes
    # command: php-fpm # Ensures the main container runs PHP after the init tasks are done

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${APP_PORT_MYSQL}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}          # Name of your database
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}     # Root password for MySQL
      MYSQL_USER: ${DB_USERNAME}              # Regular database user (DO NOT set to root)
      MYSQL_PASSWORD: ${DB_PASSWORD}          # Password for the regular user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_HOST: '%'                    # Allow root connections from any host
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT_NGINX}:80
    volumes:
      - ./src:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-php
    volumes:
      - ./src:/var/www
      - ./docker-compose/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - ${APP_PORT_PHP}:9000
    networks:
      - laravel
    working_dir: /var/www
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_START_WITH_REQUEST=yes

  adminer_container:
    image: adminer:latest
    container_name: ${APP_NAME}-adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - ${APP_PORT_ADMINER}:8080
    networks:
      - laravel

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    restart: always
    ports:
      - ${APP_PORT_PHPMYADMIN}:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel

  init:
    image: laravel
    container_name: ${APP_NAME}-init
    depends_on:
      - mysql
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - laravel
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_START_WITH_REQUEST=yes
    entrypoint: >
      sh -c "
         echo 'Waiting for 1 minute to ensure MySQL is ready...';
         sleep 60 &&
         echo 'Proceeding with initialization...' &&
         composer install &&
         php artisan migrate &&
         echo 'Initialization complete!';
         exit 0;
      "
    restart: "no" # Ensure this container exits after running the tasks

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
